//this is the JSON file of 7 tracks that returned from Spotify API

export const spotifyApiData = {
         tracks: [
           {
             album: {
               album_type: "album",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/4sD9znwiVFx9cgRPZ42aQ1",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/4sD9znwiVFx9cgRPZ42aQ1",
                   id: "4sD9znwiVFx9cgRPZ42aQ1",
                   name: "Sinéad O'Connor",
                   type: "artist",
                   uri: "spotify:artist:4sD9znwiVFx9cgRPZ42aQ1",
                 },
               ],
               available_markets: [
                 "AD",
                 "AE",
                 "AL",
                 "AR",
                 "AT",
                 "AU",
                 "BA",
                 "BE",
                 "BG",
                 "BH",
                 "BO",
                 "BR",
                 "BY",
                 "CA",
                 "CH",
                 "CL",
                 "CO",
                 "CR",
                 "CY",
                 "CZ",
                 "DE",
                 "DK",
                 "DO",
                 "DZ",
                 "EC",
                 "EE",
                 "EG",
                 "ES",
                 "FI",
                 "FR",
                 "GB",
                 "GR",
                 "GT",
                 "HK",
                 "HN",
                 "HR",
                 "HU",
                 "ID",
                 "IE",
                 "IL",
                 "IN",
                 "IS",
                 "IT",
                 "JO",
                 "JP",
                 "KW",
                 "KZ",
                 "LB",
                 "LI",
                 "LT",
                 "LU",
                 "LV",
                 "MA",
                 "MC",
                 "MD",
                 "ME",
                 "MK",
                 "MT",
                 "MX",
                 "MY",
                 "NI",
                 "NL",
                 "NO",
                 "NZ",
                 "OM",
                 "PA",
                 "PE",
                 "PH",
                 "PL",
                 "PS",
                 "PT",
                 "PY",
                 "QA",
                 "RO",
                 "RS",
                 "RU",
                 "SA",
                 "SE",
                 "SG",
                 "SI",
                 "SK",
                 "SV",
                 "TH",
                 "TN",
                 "TR",
                 "TW",
                 "UA",
                 "US",
                 "UY",
                 "VN",
                 "XK",
                 "ZA",
               ],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/34hQFIwGTLf03BZQmGL0iy",
               },
               href: "https://api.spotify.com/v1/albums/34hQFIwGTLf03BZQmGL0iy",
               id: "34hQFIwGTLf03BZQmGL0iy",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b2736f6536c2e326fb2b42db90f8",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e026f6536c2e326fb2b42db90f8",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d000048516f6536c2e326fb2b42db90f8",
                   width: 64,
                 },
               ],
               name: "I Do Not Want What I Haven't Got",
               release_date: "1990-07-01",
               release_date_precision: "day",
               total_tracks: 10,
               type: "album",
               uri: "spotify:album:34hQFIwGTLf03BZQmGL0iy",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/4sD9znwiVFx9cgRPZ42aQ1",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/4sD9znwiVFx9cgRPZ42aQ1",
                 id: "4sD9znwiVFx9cgRPZ42aQ1",
                 name: "Sinéad O'Connor",
                 type: "artist",
                 uri: "spotify:artist:4sD9znwiVFx9cgRPZ42aQ1",
               },
             ],
             available_markets: [
               "AD",
               "AE",
               "AL",
               "AR",
               "AT",
               "AU",
               "BA",
               "BE",
               "BG",
               "BH",
               "BO",
               "BR",
               "BY",
               "CA",
               "CH",
               "CL",
               "CO",
               "CR",
               "CY",
               "CZ",
               "DE",
               "DK",
               "DO",
               "DZ",
               "EC",
               "EE",
               "EG",
               "ES",
               "FI",
               "FR",
               "GB",
               "GR",
               "GT",
               "HK",
               "HN",
               "HR",
               "HU",
               "ID",
               "IE",
               "IL",
               "IN",
               "IS",
               "IT",
               "JO",
               "JP",
               "KW",
               "KZ",
               "LB",
               "LI",
               "LT",
               "LU",
               "LV",
               "MA",
               "MC",
               "MD",
               "ME",
               "MK",
               "MT",
               "MX",
               "MY",
               "NI",
               "NL",
               "NO",
               "NZ",
               "OM",
               "PA",
               "PE",
               "PH",
               "PL",
               "PS",
               "PT",
               "PY",
               "QA",
               "RO",
               "RS",
               "RU",
               "SA",
               "SE",
               "SG",
               "SI",
               "SK",
               "SV",
               "TH",
               "TN",
               "TR",
               "TW",
               "UA",
               "US",
               "UY",
               "VN",
               "XK",
               "ZA",
             ],
             disc_number: 1,
             duration_ms: 280040,
             explicit: false,
             external_ids: {
               isrc: "GBAYK9000017",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/3nvuPQTw2zuFAVuLsC9IYQ",
             },
             href: "https://api.spotify.com/v1/tracks/3nvuPQTw2zuFAVuLsC9IYQ",
             id: "3nvuPQTw2zuFAVuLsC9IYQ",
             is_local: false,
             name: "Nothing Compares 2 U",
             popularity: 75,
             preview_url:
               "https://p.scdn.co/mp3-preview/d50d7c8ec55e72b1fef322107cc76ac5ade9c1b6?cid=956e408b3a2d492183230f72c33ca134",
             track_number: 6,
             type: "track",
             uri: "spotify:track:3nvuPQTw2zuFAVuLsC9IYQ",
           },
           {
             album: {
               album_type: "compilation",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/2DaxqgrOhkeH0fpeiQq2f4",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/2DaxqgrOhkeH0fpeiQq2f4",
                   id: "2DaxqgrOhkeH0fpeiQq2f4",
                   name: "Oasis",
                   type: "artist",
                   uri: "spotify:artist:2DaxqgrOhkeH0fpeiQq2f4",
                 },
               ],
               available_markets: [],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/1f4I0SpE0O8yg4Eg2ywwv1",
               },
               href: "https://api.spotify.com/v1/albums/1f4I0SpE0O8yg4Eg2ywwv1",
               id: "1f4I0SpE0O8yg4Eg2ywwv1",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b2735160562feff92ba667f0c39f",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e025160562feff92ba667f0c39f",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d000048515160562feff92ba667f0c39f",
                   width: 64,
                 },
               ],
               name: "Stop The Clocks",
               release_date: "2006-11-19",
               release_date_precision: "day",
               total_tracks: 18,
               type: "album",
               uri: "spotify:album:1f4I0SpE0O8yg4Eg2ywwv1",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/2DaxqgrOhkeH0fpeiQq2f4",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/2DaxqgrOhkeH0fpeiQq2f4",
                 id: "2DaxqgrOhkeH0fpeiQq2f4",
                 name: "Oasis",
                 type: "artist",
                 uri: "spotify:artist:2DaxqgrOhkeH0fpeiQq2f4",
               },
             ],
             available_markets: [],
             disc_number: 1,
             duration_ms: 258613,
             explicit: false,
             external_ids: {
               isrc: "GBAAW9500189",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/2CT3r93YuSHtm57mjxvjhH",
             },
             href: "https://api.spotify.com/v1/tracks/2CT3r93YuSHtm57mjxvjhH",
             id: "2CT3r93YuSHtm57mjxvjhH",
             is_local: false,
             name: "Wonderwall",
             popularity: 0,
             preview_url: null,
             track_number: 6,
             type: "track",
             uri: "spotify:track:2CT3r93YuSHtm57mjxvjhH",
           },
           {
             album: {
               album_type: "compilation",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                   id: "0LyfQWJT6nXafLPZqxe9Of",
                   name: "Various Artists",
                   type: "artist",
                   uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
                 },
               ],
               available_markets: [
                 "AD",
                 "AE",
                 "AL",
                 "AT",
                 "BA",
                 "BE",
                 "BG",
                 "BH",
                 "CH",
                 "CY",
                 "CZ",
                 "DE",
                 "DK",
                 "EE",
                 "ES",
                 "FI",
                 "FR",
                 "GB",
                 "GR",
                 "HR",
                 "HU",
                 "IE",
                 "IL",
                 "IS",
                 "IT",
                 "JO",
                 "KW",
                 "LB",
                 "LI",
                 "LT",
                 "LU",
                 "LV",
                 "MC",
                 "ME",
                 "MK",
                 "MT",
                 "NL",
                 "NO",
                 "OM",
                 "PL",
                 "PT",
                 "QA",
                 "RO",
                 "RS",
                 "SA",
                 "SE",
                 "SI",
                 "SK",
                 "TR",
                 "UA",
                 "XK",
                 "ZA",
               ],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/4RADzQiLlSpZXXJ7bnyDqs",
               },
               href: "https://api.spotify.com/v1/albums/4RADzQiLlSpZXXJ7bnyDqs",
               id: "4RADzQiLlSpZXXJ7bnyDqs",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b2737539211a572a05f453bfca65",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e027539211a572a05f453bfca65",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d000048517539211a572a05f453bfca65",
                   width: 64,
                 },
               ],
               name: "Tarzan Original Soundtrack (German Version)",
               release_date: "1999-01-01",
               release_date_precision: "day",
               total_tracks: 16,
               type: "album",
               uri: "spotify:album:4RADzQiLlSpZXXJ7bnyDqs",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/4lxfqrEsLX6N1N4OCSkILp",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/4lxfqrEsLX6N1N4OCSkILp",
                 id: "4lxfqrEsLX6N1N4OCSkILp",
                 name: "Phil Collins",
                 type: "artist",
                 uri: "spotify:artist:4lxfqrEsLX6N1N4OCSkILp",
               },
             ],
             available_markets: [
               "AD",
               "AE",
               "AL",
               "AT",
               "BA",
               "BE",
               "BG",
               "BH",
               "CH",
               "CY",
               "CZ",
               "DE",
               "DK",
               "EE",
               "ES",
               "FI",
               "FR",
               "GB",
               "GR",
               "HR",
               "HU",
               "IE",
               "IL",
               "IS",
               "IT",
               "JO",
               "KW",
               "LB",
               "LI",
               "LT",
               "LU",
               "LV",
               "MC",
               "ME",
               "MK",
               "MT",
               "NL",
               "NO",
               "OM",
               "PL",
               "PT",
               "QA",
               "RO",
               "RS",
               "SA",
               "SE",
               "SI",
               "SK",
               "TR",
               "UA",
               "XK",
               "ZA",
             ],
             disc_number: 1,
             duration_ms: 258399,
             explicit: false,
             external_ids: {
               isrc: "USWD10110146",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/0LXosXV9ZvmzIpzUsOMuLv",
             },
             href: "https://api.spotify.com/v1/tracks/0LXosXV9ZvmzIpzUsOMuLv",
             id: "0LXosXV9ZvmzIpzUsOMuLv",
             is_local: false,
             name: "You'll Be In My Heart",
             popularity: 65,
             preview_url: null,
             track_number: 7,
             type: "track",
             uri: "spotify:track:0LXosXV9ZvmzIpzUsOMuLv",
           },
           {
             album: {
               album_type: "album",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/26dSoYclwsYLMAKD3tpOr4",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/26dSoYclwsYLMAKD3tpOr4",
                   id: "26dSoYclwsYLMAKD3tpOr4",
                   name: "Britney Spears",
                   type: "artist",
                   uri: "spotify:artist:26dSoYclwsYLMAKD3tpOr4",
                 },
               ],
               available_markets: [
                 "AD",
                 "AE",
                 "AL",
                 "AR",
                 "AT",
                 "AU",
                 "BA",
                 "BE",
                 "BG",
                 "BH",
                 "BO",
                 "BR",
                 "BY",
                 "CA",
                 "CH",
                 "CL",
                 "CO",
                 "CR",
                 "CY",
                 "CZ",
                 "DE",
                 "DK",
                 "DO",
                 "DZ",
                 "EC",
                 "EE",
                 "EG",
                 "ES",
                 "FI",
                 "FR",
                 "GB",
                 "GR",
                 "GT",
                 "HK",
                 "HN",
                 "HR",
                 "HU",
                 "ID",
                 "IE",
                 "IL",
                 "IN",
                 "IS",
                 "IT",
                 "JO",
                 "JP",
                 "KW",
                 "KZ",
                 "LB",
                 "LI",
                 "LT",
                 "LU",
                 "LV",
                 "MA",
                 "MC",
                 "MD",
                 "ME",
                 "MK",
                 "MT",
                 "MX",
                 "MY",
                 "NI",
                 "NL",
                 "NO",
                 "NZ",
                 "OM",
                 "PA",
                 "PE",
                 "PH",
                 "PL",
                 "PS",
                 "PT",
                 "PY",
                 "QA",
                 "RO",
                 "RS",
                 "RU",
                 "SA",
                 "SE",
                 "SG",
                 "SI",
                 "SK",
                 "SV",
                 "TH",
                 "TN",
                 "TR",
                 "TW",
                 "UA",
                 "US",
                 "UY",
                 "VN",
                 "XK",
                 "ZA",
               ],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/3WNxdumkSMGMJRhEgK80qx",
               },
               href: "https://api.spotify.com/v1/albums/3WNxdumkSMGMJRhEgK80qx",
               id: "3WNxdumkSMGMJRhEgK80qx",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b2738e49866860c25afffe2f1a02",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e028e49866860c25afffe2f1a02",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d000048518e49866860c25afffe2f1a02",
                   width: 64,
                 },
               ],
               name: "...Baby One More Time (Digital Deluxe Version)",
               release_date: "1999-01-12",
               release_date_precision: "day",
               total_tracks: 16,
               type: "album",
               uri: "spotify:album:3WNxdumkSMGMJRhEgK80qx",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/26dSoYclwsYLMAKD3tpOr4",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/26dSoYclwsYLMAKD3tpOr4",
                 id: "26dSoYclwsYLMAKD3tpOr4",
                 name: "Britney Spears",
                 type: "artist",
                 uri: "spotify:artist:26dSoYclwsYLMAKD3tpOr4",
               },
             ],
             available_markets: [
               "AD",
               "AE",
               "AL",
               "AR",
               "AT",
               "AU",
               "BA",
               "BE",
               "BG",
               "BH",
               "BO",
               "BR",
               "BY",
               "CA",
               "CH",
               "CL",
               "CO",
               "CR",
               "CY",
               "CZ",
               "DE",
               "DK",
               "DO",
               "DZ",
               "EC",
               "EE",
               "EG",
               "ES",
               "FI",
               "FR",
               "GB",
               "GR",
               "GT",
               "HK",
               "HN",
               "HR",
               "HU",
               "ID",
               "IE",
               "IL",
               "IN",
               "IS",
               "IT",
               "JO",
               "JP",
               "KW",
               "KZ",
               "LB",
               "LI",
               "LT",
               "LU",
               "LV",
               "MA",
               "MC",
               "MD",
               "ME",
               "MK",
               "MT",
               "MX",
               "MY",
               "NI",
               "NL",
               "NO",
               "NZ",
               "OM",
               "PA",
               "PE",
               "PH",
               "PL",
               "PS",
               "PT",
               "PY",
               "QA",
               "RO",
               "RS",
               "RU",
               "SA",
               "SE",
               "SG",
               "SI",
               "SK",
               "SV",
               "TH",
               "TN",
               "TR",
               "TW",
               "UA",
               "US",
               "UY",
               "VN",
               "XK",
               "ZA",
             ],
             disc_number: 1,
             duration_ms: 245066,
             explicit: false,
             external_ids: {
               isrc: "USJI19910452",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/1UI0l2L66HJ9AtoEOlHzv4",
             },
             href: "https://api.spotify.com/v1/tracks/1UI0l2L66HJ9AtoEOlHzv4",
             id: "1UI0l2L66HJ9AtoEOlHzv4",
             is_local: false,
             name: "Sometimes",
             popularity: 69,
             preview_url:
               "https://p.scdn.co/mp3-preview/66534231ccdd99619485b6ea4fa90987322dd812?cid=956e408b3a2d492183230f72c33ca134",
             track_number: 3,
             type: "track",
             uri: "spotify:track:1UI0l2L66HJ9AtoEOlHzv4",
           },
           {
             album: {
               album_type: "album",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/3nnQpaTvKb5jCQabZefACI",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/3nnQpaTvKb5jCQabZefACI",
                   id: "3nnQpaTvKb5jCQabZefACI",
                   name: "Jeff Buckley",
                   type: "artist",
                   uri: "spotify:artist:3nnQpaTvKb5jCQabZefACI",
                 },
               ],
               available_markets: [],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/07Fr36M0hRPJrSJMFWGnvD",
               },
               href: "https://api.spotify.com/v1/albums/07Fr36M0hRPJrSJMFWGnvD",
               id: "07Fr36M0hRPJrSJMFWGnvD",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b273c9e961be2679c41930a370cd",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e02c9e961be2679c41930a370cd",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d00004851c9e961be2679c41930a370cd",
                   width: 64,
                 },
               ],
               name: "Grace (Legacy Edition)",
               release_date: "1994",
               release_date_precision: "year",
               total_tracks: 22,
               type: "album",
               uri: "spotify:album:07Fr36M0hRPJrSJMFWGnvD",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/3nnQpaTvKb5jCQabZefACI",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/3nnQpaTvKb5jCQabZefACI",
                 id: "3nnQpaTvKb5jCQabZefACI",
                 name: "Jeff Buckley",
                 type: "artist",
                 uri: "spotify:artist:3nnQpaTvKb5jCQabZefACI",
               },
             ],
             available_markets: [],
             disc_number: 1,
             duration_ms: 413320,
             explicit: false,
             external_ids: {
               isrc: "USSM19400915",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/74X1epeRufHckhuX1KFD04",
             },
             href: "https://api.spotify.com/v1/tracks/74X1epeRufHckhuX1KFD04",
             id: "74X1epeRufHckhuX1KFD04",
             is_local: false,
             name: "Hallelujah",
             popularity: 5,
             preview_url: null,
             track_number: 6,
             type: "track",
             uri: "spotify:track:74X1epeRufHckhuX1KFD04",
           },
           {
             album: {
               album_type: "album",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/2VZNmg4vCnew4Pavo8zDdW",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/2VZNmg4vCnew4Pavo8zDdW",
                   id: "2VZNmg4vCnew4Pavo8zDdW",
                   name: "Max Richter",
                   type: "artist",
                   uri: "spotify:artist:2VZNmg4vCnew4Pavo8zDdW",
                 },
               ],
               available_markets: [
                 "AD",
                 "AE",
                 "AL",
                 "AR",
                 "AT",
                 "AU",
                 "BA",
                 "BE",
                 "BG",
                 "BH",
                 "BO",
                 "BR",
                 "BY",
                 "CA",
                 "CH",
                 "CL",
                 "CO",
                 "CR",
                 "CY",
                 "CZ",
                 "DE",
                 "DK",
                 "DO",
                 "DZ",
                 "EC",
                 "EE",
                 "EG",
                 "ES",
                 "FI",
                 "FR",
                 "GB",
                 "GR",
                 "GT",
                 "HK",
                 "HN",
                 "HR",
                 "HU",
                 "ID",
                 "IE",
                 "IL",
                 "IN",
                 "IS",
                 "IT",
                 "JO",
                 "JP",
                 "KW",
                 "KZ",
                 "LB",
                 "LI",
                 "LT",
                 "LU",
                 "LV",
                 "MA",
                 "MC",
                 "MD",
                 "ME",
                 "MK",
                 "MT",
                 "MX",
                 "MY",
                 "NI",
                 "NL",
                 "NO",
                 "NZ",
                 "OM",
                 "PA",
                 "PE",
                 "PH",
                 "PL",
                 "PS",
                 "PT",
                 "PY",
                 "QA",
                 "RO",
                 "RS",
                 "RU",
                 "SA",
                 "SE",
                 "SG",
                 "SI",
                 "SK",
                 "SV",
                 "TH",
                 "TN",
                 "TR",
                 "TW",
                 "UA",
                 "US",
                 "UY",
                 "VN",
                 "XK",
                 "ZA",
               ],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/3Ndz8fhskuQ0MWWdQcLMEN",
               },
               href: "https://api.spotify.com/v1/albums/3Ndz8fhskuQ0MWWdQcLMEN",
               id: "3Ndz8fhskuQ0MWWdQcLMEN",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b27316732dafeaa4bdf128df322d",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e0216732dafeaa4bdf128df322d",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d0000485116732dafeaa4bdf128df322d",
                   width: 64,
                 },
               ],
               name: "Voices",
               release_date: "2020-07-31",
               release_date_precision: "day",
               total_tracks: 50,
               type: "album",
               uri: "spotify:album:3Ndz8fhskuQ0MWWdQcLMEN",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/2VZNmg4vCnew4Pavo8zDdW",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/2VZNmg4vCnew4Pavo8zDdW",
                 id: "2VZNmg4vCnew4Pavo8zDdW",
                 name: "Max Richter",
                 type: "artist",
                 uri: "spotify:artist:2VZNmg4vCnew4Pavo8zDdW",
               },
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/6XHc5bOPo6tCfP92bbhNa4",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/6XHc5bOPo6tCfP92bbhNa4",
                 id: "6XHc5bOPo6tCfP92bbhNa4",
                 name: "KiKi Layne",
                 type: "artist",
                 uri: "spotify:artist:6XHc5bOPo6tCfP92bbhNa4",
               },
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/670EXb4x6t2MAvRvqCixyx",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/670EXb4x6t2MAvRvqCixyx",
                 id: "670EXb4x6t2MAvRvqCixyx",
                 name: "Mari Samuelsen",
                 type: "artist",
                 uri: "spotify:artist:670EXb4x6t2MAvRvqCixyx",
               },
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/6c3mMiMnHQtu4mGWN87CFx",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/6c3mMiMnHQtu4mGWN87CFx",
                 id: "6c3mMiMnHQtu4mGWN87CFx",
                 name: "Robert Ziegler",
                 type: "artist",
                 uri: "spotify:artist:6c3mMiMnHQtu4mGWN87CFx",
               },
             ],
             available_markets: [
               "AD",
               "AE",
               "AL",
               "AR",
               "AT",
               "AU",
               "BA",
               "BE",
               "BG",
               "BH",
               "BO",
               "BR",
               "BY",
               "CA",
               "CH",
               "CL",
               "CO",
               "CR",
               "CY",
               "CZ",
               "DE",
               "DK",
               "DO",
               "DZ",
               "EC",
               "EE",
               "EG",
               "ES",
               "FI",
               "FR",
               "GB",
               "GR",
               "GT",
               "HK",
               "HN",
               "HR",
               "HU",
               "ID",
               "IE",
               "IL",
               "IN",
               "IS",
               "IT",
               "JO",
               "JP",
               "KW",
               "KZ",
               "LB",
               "LI",
               "LT",
               "LU",
               "LV",
               "MA",
               "MC",
               "MD",
               "ME",
               "MK",
               "MT",
               "MX",
               "MY",
               "NI",
               "NL",
               "NO",
               "NZ",
               "OM",
               "PA",
               "PE",
               "PH",
               "PL",
               "PS",
               "PT",
               "PY",
               "QA",
               "RO",
               "RS",
               "RU",
               "SA",
               "SE",
               "SG",
               "SI",
               "SK",
               "SV",
               "TH",
               "TN",
               "TR",
               "TW",
               "UA",
               "US",
               "UY",
               "VN",
               "XK",
               "ZA",
             ],
             disc_number: 1,
             duration_ms: 74826,
             explicit: false,
             external_ids: {
               isrc: "GBUM72002460",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/1V7VAMQQwJoHECiuaG36Pb",
             },
             href: "https://api.spotify.com/v1/tracks/1V7VAMQQwJoHECiuaG36Pb",
             id: "1V7VAMQQwJoHECiuaG36Pb",
             is_local: false,
             name: "All Human Beings - Pt. 4",
             popularity: 43,
             preview_url: null,
             track_number: 4,
             type: "track",
             uri: "spotify:track:1V7VAMQQwJoHECiuaG36Pb",
           },
           {
             album: {
               album_type: "album",
               artists: [
                 {
                   external_urls: {
                     spotify:
                       "https://open.spotify.com/artist/37w38cCSGgKLdayTRjna4W",
                   },
                   href:
                     "https://api.spotify.com/v1/artists/37w38cCSGgKLdayTRjna4W",
                   id: "37w38cCSGgKLdayTRjna4W",
                   name: "Mazzy Star",
                   type: "artist",
                   uri: "spotify:artist:37w38cCSGgKLdayTRjna4W",
                 },
               ],
               available_markets: [
                 "AD",
                 "AE",
                 "AL",
                 "AR",
                 "AT",
                 "AU",
                 "BA",
                 "BE",
                 "BG",
                 "BH",
                 "BO",
                 "BR",
                 "BY",
                 "CA",
                 "CH",
                 "CL",
                 "CO",
                 "CR",
                 "CY",
                 "CZ",
                 "DE",
                 "DK",
                 "DO",
                 "DZ",
                 "EC",
                 "EE",
                 "EG",
                 "ES",
                 "FI",
                 "FR",
                 "GB",
                 "GR",
                 "GT",
                 "HK",
                 "HN",
                 "HR",
                 "HU",
                 "ID",
                 "IE",
                 "IL",
                 "IN",
                 "IS",
                 "IT",
                 "JO",
                 "JP",
                 "KW",
                 "KZ",
                 "LB",
                 "LI",
                 "LT",
                 "LU",
                 "LV",
                 "MA",
                 "MC",
                 "MD",
                 "ME",
                 "MK",
                 "MT",
                 "MX",
                 "MY",
                 "NI",
                 "NL",
                 "NO",
                 "NZ",
                 "OM",
                 "PA",
                 "PE",
                 "PH",
                 "PL",
                 "PS",
                 "PT",
                 "PY",
                 "QA",
                 "RO",
                 "RS",
                 "RU",
                 "SA",
                 "SE",
                 "SG",
                 "SI",
                 "SK",
                 "SV",
                 "TH",
                 "TN",
                 "TR",
                 "TW",
                 "UA",
                 "US",
                 "UY",
                 "VN",
                 "XK",
                 "ZA",
               ],
               external_urls: {
                 spotify:
                   "https://open.spotify.com/album/5K18gTgac0q6Jma5HkV1vA",
               },
               href: "https://api.spotify.com/v1/albums/5K18gTgac0q6Jma5HkV1vA",
               id: "5K18gTgac0q6Jma5HkV1vA",
               images: [
                 {
                   height: 640,
                   url:
                     "https://i.scdn.co/image/ab67616d0000b27389a392107ebd79818022b3ea",
                   width: 640,
                 },
                 {
                   height: 300,
                   url:
                     "https://i.scdn.co/image/ab67616d00001e0289a392107ebd79818022b3ea",
                   width: 300,
                 },
                 {
                   height: 64,
                   url:
                     "https://i.scdn.co/image/ab67616d0000485189a392107ebd79818022b3ea",
                   width: 64,
                 },
               ],
               name: "So Tonight That I Might See",
               release_date: "1993-01-01",
               release_date_precision: "day",
               total_tracks: 10,
               type: "album",
               uri: "spotify:album:5K18gTgac0q6Jma5HkV1vA",
             },
             artists: [
               {
                 external_urls: {
                   spotify:
                     "https://open.spotify.com/artist/37w38cCSGgKLdayTRjna4W",
                 },
                 href:
                   "https://api.spotify.com/v1/artists/37w38cCSGgKLdayTRjna4W",
                 id: "37w38cCSGgKLdayTRjna4W",
                 name: "Mazzy Star",
                 type: "artist",
                 uri: "spotify:artist:37w38cCSGgKLdayTRjna4W",
               },
             ],
             available_markets: [
               "AD",
               "AE",
               "AL",
               "AR",
               "AT",
               "AU",
               "BA",
               "BE",
               "BG",
               "BH",
               "BO",
               "BR",
               "BY",
               "CA",
               "CH",
               "CL",
               "CO",
               "CR",
               "CY",
               "CZ",
               "DE",
               "DK",
               "DO",
               "DZ",
               "EC",
               "EE",
               "EG",
               "ES",
               "FI",
               "FR",
               "GB",
               "GR",
               "GT",
               "HK",
               "HN",
               "HR",
               "HU",
               "ID",
               "IE",
               "IL",
               "IN",
               "IS",
               "IT",
               "JO",
               "JP",
               "KW",
               "KZ",
               "LB",
               "LI",
               "LT",
               "LU",
               "LV",
               "MA",
               "MC",
               "MD",
               "ME",
               "MK",
               "MT",
               "MX",
               "MY",
               "NI",
               "NL",
               "NO",
               "NZ",
               "OM",
               "PA",
               "PE",
               "PH",
               "PL",
               "PS",
               "PT",
               "PY",
               "QA",
               "RO",
               "RS",
               "RU",
               "SA",
               "SE",
               "SG",
               "SI",
               "SK",
               "SV",
               "TH",
               "TN",
               "TR",
               "TW",
               "UA",
               "US",
               "UY",
               "VN",
               "XK",
               "ZA",
             ],
             disc_number: 1,
             duration_ms: 295600,
             explicit: false,
             external_ids: {
               isrc: "USCA29300105",
             },
             external_urls: {
               spotify: "https://open.spotify.com/track/1LzNfuep1bnAUR9skqdHCK",
             },
             href: "https://api.spotify.com/v1/tracks/1LzNfuep1bnAUR9skqdHCK",
             id: "1LzNfuep1bnAUR9skqdHCK",
             is_local: false,
             name: "Fade Into You",
             popularity: 72,
             preview_url: null,
             track_number: 1,
             type: "track",
             uri: "spotify:track:1LzNfuep1bnAUR9skqdHCK",
           },
         ],
       }